// Code generated by ifacemaker; DO NOT EDIT.

package kubernetes

import (
	"context"
)

// HelmInstaller ...
type HelmInstaller interface {
	// ApproveEverestMonitoringInstallPlan approves the install plans needed for installing the monitoring operators.
	ApproveEverestMonitoringInstallPlan(ctx context.Context) error
	// ApproveEverestMonitoringInstallPlan approves the install plans needed for installing the everest operator.
	ApproveEverestOperatorInstallPlan(context.Context) error
	// ApproveEverestMonitoringInstallPlan approves the install plans needed for installing the DB namespaces.
	ApproveDBNamespacesInstallPlans(context.Context) error
}
