// Code generated by ifacemaker; DO NOT EDIT.

package kubernetes

import (
	"context"

	goversion "github.com/hashicorp/go-version"
)

// HelmInstaller ...
type HelmInstaller interface {
	// ApproveEverestMonitoringInstallPlan approves the install plans needed for installing the monitoring operators.
	ApproveEverestMonitoringInstallPlan(ctx context.Context) error
	// ApproveEverestOperatorInstallPlan approves the install plans needed for installing the everest operator.
	ApproveEverestOperatorInstallPlan(ctx context.Context, version *goversion.Version) error
	// ApproveDBNamespacesInstallPlans approves the install plans needed for installing the DB namespaces.
	ApproveDBNamespacesInstallPlans(ctx context.Context) error
	// DeleteOLM deletes the required OLM components.
	DeleteOLM(ctx context.Context) error
	// DeleteAllBackupStorages deletes all monitoring instances in the system.
	DeleteAllBackupStorages(ctx context.Context) error
	// DeleteAllMonitoringInstances deletes all monitoring instances in the system.
	DeleteAllMonitoringInstances(ctx context.Context) error
	// DeleteAllDatabaseClusters deletes all database clusters.
	DeleteAllDatabaseClusters(ctx context.Context) error
}
