name: "🐛 Bug Report"
description: Create a report to help us improve OpenEverest
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! 
        
        We are most likely to fix bugs that are easy to reproduce, so please provide detailed steps.
        
        **Before submitting, please search to see if an issue already exists:**
        - [Search OpenEverest Issues](https://github.com/openeverest/openeverest/issues)

  - type: textarea
    id: issue-description
    attributes:
      label: What is the issue?
      description: A clear and concise description of the bug. What happened versus what you expected to happen?
      placeholder: |
        I tried to do X...
        I expected Y to happen...
        But instead Z happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide a minimal example or list the steps to reproduce the issue.
      placeholder: |
        1. Run command '...'
        2. Create resource '...'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Output
      description: |
        Please include relevant logs, error output, or screenshots. 
        (Tip: Wrap code/logs in triple backticks ``` for better formatting).
      placeholder: |
        ```bash
        Error: something went wrong
        ```
  
  - type: input
    id: version
    attributes:
      label: OpenEverest Version
      description: What version of OpenEverest are you running?
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install OpenEverest?
      options:
        - Helm
        - CLI (everestctl)
        - Manifests / Manual
    validations:
      required: true

  - type: dropdown
    id: k8s-distro
    attributes:
      label: Kubernetes Distribution
      description: Where are you running Kubernetes?
      options:
        - GKE
        - AKS
        - EKS
        - OpenShift
        - DigitalOcean
        - kind
        - minikube
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide additional details about your environment (K8s version, OS, Cloud Provider, etc.).
      placeholder: |
        Kubernetes Version: v1.28.0
        Host OS: Ubuntu 22.04
        Cloud Provider: AWS
  
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If you have suggestions on how to fix this, please let us know.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., screenshots).
