---
name: 'Adjust GitHub worker node'
inputs:
  adjust-host-for-k3d:
    description: 'Adjust host for K3D cluster'
    required: false
    default: false
  mount-docker-data:
    description: 'Mount Docker data directory to /mnt to have more space'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    # GitHub worker node has enabled AppArmor profile for Docker.
    # Use this step when AppArmor creates issues with running application in Docker container (like PXC).
    - name: Adjust host for K3D cluster
      if: ${{ inputs.adjust-host-for-k3d == 'true' }}
      continue-on-error: true
      shell: bash
      run: |
        sudo modprobe br_netfilter
        sudo systemctl stop apparmor
        sudo aa-teardown

    # Switch docker data directory to /mnt to have more space for the local Kubernetes cluster
    - name: Switch docker-daemon data directory to /mnt
      if: ${{ inputs.mount-docker-data == 'true' }}
      shell: bash
      run: |
        sudo systemctl stop docker
        echo '{ "exec-opts": ["native.cgroupdriver=cgroupfs"], "cgroup-parent": "/actions_job", "data-root": "/mnt/docker-data" }' | sudo tee /etc/docker/daemon.json
        sudo mkdir /mnt/docker-data
        sudo systemctl start docker
