// Code generated by mockery v2.43.2. DO NOT EDIT.

package rbac

import mock "github.com/stretchr/testify/mock"

// MockEnforcer is an autogenerated mock type for the Enforcer type
type MockEnforcer struct {
	mock.Mock
}

// Enforce provides a mock function with given fields: v
func (_m *MockEnforcer) Enforce(v ...interface{}) (bool, error) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Enforce")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return rf(v...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(v...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(v...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEnforcer creates a new instance of MockEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockEnforcer {
	mock := &MockEnforcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
